#!/bin/sh

# Ensure the prepare-commit-msg hook is installed
if [ ! -f .git/hooks/prepare-commit-msg ]; then
  echo "Installing prepare-commit-msg hook..."
  cp scripts/git-hooks/prepare-commit-msg .git/hooks/ && chmod +x .git/hooks/prepare-commit-msg
fi 